package com.lcgang.ticketComing.models;

import java.util.Date;

public class Tickets {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.id
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.title
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.images
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.longitude
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    private Float longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.latitude
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    private Float latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.geohash
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    private String geohash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.create_time
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.update_time
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.show_times
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    private Long showTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.reward_times
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    private Integer rewardTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.reward_amount
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    private Float rewardAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets.comment_times
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    private Integer commentTimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.id
     *
     * @return the value of tickets.id
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.id
     *
     * @param id the value for tickets.id
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.title
     *
     * @return the value of tickets.title
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.title
     *
     * @param title the value for tickets.title
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.images
     *
     * @return the value of tickets.images
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.images
     *
     * @param images the value for tickets.images
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.longitude
     *
     * @return the value of tickets.longitude
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.longitude
     *
     * @param longitude the value for tickets.longitude
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.latitude
     *
     * @return the value of tickets.latitude
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.latitude
     *
     * @param latitude the value for tickets.latitude
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.geohash
     *
     * @return the value of tickets.geohash
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public String getGeohash() {
        return geohash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.geohash
     *
     * @param geohash the value for tickets.geohash
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public void setGeohash(String geohash) {
        this.geohash = geohash == null ? null : geohash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.create_time
     *
     * @return the value of tickets.create_time
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.create_time
     *
     * @param createTime the value for tickets.create_time
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.update_time
     *
     * @return the value of tickets.update_time
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.update_time
     *
     * @param updateTime the value for tickets.update_time
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.show_times
     *
     * @return the value of tickets.show_times
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public Long getShowTimes() {
        return showTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.show_times
     *
     * @param showTimes the value for tickets.show_times
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public void setShowTimes(Long showTimes) {
        this.showTimes = showTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.reward_times
     *
     * @return the value of tickets.reward_times
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public Integer getRewardTimes() {
        return rewardTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.reward_times
     *
     * @param rewardTimes the value for tickets.reward_times
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public void setRewardTimes(Integer rewardTimes) {
        this.rewardTimes = rewardTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.reward_amount
     *
     * @return the value of tickets.reward_amount
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public Float getRewardAmount() {
        return rewardAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.reward_amount
     *
     * @param rewardAmount the value for tickets.reward_amount
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public void setRewardAmount(Float rewardAmount) {
        this.rewardAmount = rewardAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets.comment_times
     *
     * @return the value of tickets.comment_times
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public Integer getCommentTimes() {
        return commentTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets.comment_times
     *
     * @param commentTimes the value for tickets.comment_times
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    public void setCommentTimes(Integer commentTimes) {
        this.commentTimes = commentTimes;
    }
}