package com.lcgang.ticketComing.models;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.openId
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.longitude
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    private Float longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.latitude
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    private Float latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.geohash
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    private String geohash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.create_time
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.update_time
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.openId
     *
     * @return the value of users.openId
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.openId
     *
     * @param openid the value for users.openId
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.longitude
     *
     * @return the value of users.longitude
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.longitude
     *
     * @param longitude the value for users.longitude
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.latitude
     *
     * @return the value of users.latitude
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.latitude
     *
     * @param latitude the value for users.latitude
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.geohash
     *
     * @return the value of users.geohash
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    public String getGeohash() {
        return geohash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.geohash
     *
     * @param geohash the value for users.geohash
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    public void setGeohash(String geohash) {
        this.geohash = geohash == null ? null : geohash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.create_time
     *
     * @return the value of users.create_time
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.create_time
     *
     * @param createTime the value for users.create_time
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.update_time
     *
     * @return the value of users.update_time
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.update_time
     *
     * @param updateTime the value for users.update_time
     *
     * @mbg.generated Tue Jan 23 17:00:20 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}