package com.lcgang.ticketComing.mapper;

import com.lcgang.ticketComing.models.Tickets;
import com.lcgang.ticketComing.models.TicketsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TicketsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    long countByExample(TicketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    int deleteByExample(TicketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    int insert(Tickets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    int insertSelective(Tickets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    List<Tickets> selectByExample(TicketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    Tickets selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") Tickets record, @Param("example") TicketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    int updateByExample(@Param("record") Tickets record, @Param("example") TicketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    int updateByPrimaryKeySelective(Tickets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets
     *
     * @mbg.generated Thu Feb 22 14:18:22 CST 2018
     */
    int updateByPrimaryKey(Tickets record);
}